In [1]:
# 从mxnet导入ndarray这个包
import mxnet as mx
print mx.__path__
from mxnet import ndarray as nd


['/usr/local/lib/python2.7/site-packages/mxnet']


In [2]:
nd.zeros((3, 4))


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
<NDArray 3x4 @cpu(0)>

In [4]:
x = nd.ones((3,4))
x


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

In [5]:
nd.array([[1,2],[2,3]])


[[ 1.  2.]
 [ 2.  3.]]
<NDArray 2x2 @cpu(0)>

In [7]:
y = nd.random_normal(0, 1, shape=(3,4))
y


[[ 1.16307867  2.21220636  0.48380461  0.7740038 ]
 [ 0.29956347  1.04344034  0.15302546  1.18392551]
 [-1.16881478  1.89171135  1.55807114 -1.23474145]]
<NDArray 3x4 @cpu(0)>

In [8]:
y.shape

(3L, 4L)

In [9]:
y.size

12L

In [10]:
# 操作符
x + y


[[ 2.16307878  3.21220636  1.48380458  1.77400374]
 [ 1.29956341  2.04344034  1.15302551  2.18392563]
 [-0.16881478  2.89171124  2.55807114 -0.23474145]]
<NDArray 3x4 @cpu(0)>

In [11]:
x * y


[[ 1.16307867  2.21220636  0.48380461  0.7740038 ]
 [ 0.29956347  1.04344034  0.15302546  1.18392551]
 [-1.16881478  1.89171135  1.55807114 -1.23474145]]
<NDArray 3x4 @cpu(0)>

In [12]:
nd.exp(y)


[[ 3.19976926  9.13585091  1.6222347   2.16843081]
 [ 1.34926963  2.83896732  1.16535461  3.26717448]
 [ 0.31073502  6.63070631  4.74965096  0.29090998]]
<NDArray 3x4 @cpu(0)>

In [13]:
nd.dot(x, y.T)


[[ 4.63309383  2.67995477  1.04622626]
 [ 4.63309383  2.67995477  1.04622626]
 [ 4.63309383  2.67995477  1.04622626]]
<NDArray 3x3 @cpu(0)>

In [16]:
# 广播
a = nd.arange(3).reshape((3,1))
b = nd.arange(2).reshape((1,2))
print(a)
print(b)
print(a+b)


[[ 0.]
 [ 1.]
 [ 2.]]
<NDArray 3x1 @cpu(0)>

[[ 0.  1.]]
<NDArray 1x2 @cpu(0)>

[[ 0.  1.]
 [ 1.  2.]
 [ 2.  3.]]
<NDArray 3x2 @cpu(0)>


In [17]:
# 跟NumPy的转换
import numpy as np
x = np.ones((2,3))
y = nd.array(x)
z = y.asnumpy()
print([z, y])

[array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32), 
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 2x3 @cpu(0)>]


In [18]:
# 替换操作
x = nd.ones((3, 4))
y = nd.ones((3, 4))
before = id(y)
y = y+x
id(y) == before

False

In [19]:
# 把结果通过[:]写到之前开好的数组里
z = nd.zeros_like(x)
before = id(z)
z[:] = x + y
id(z) == before

True

In [20]:
# 还是为x+y创建了临时空间，然后再复制到z。为避免这个开销，可以使用操作符的全名版本中的out参数
nd.elemwise_add(x, y, out=z)
id(z) == before

True