# 2.2.1 Tensor
Tensor和numpy的ndarray类似，但 Tensor可以用GPU加速。

In [1]:
from __future__ import print_function
import torch as t

In [2]:
# 构建5x3矩阵
x = t.Tensor(5, 3)
x

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [3]:
# 用0,1均匀分布随机初始化二维数组
x = t.rand(5, 3)
x

tensor([[0.2158, 0.8559, 0.0100],
        [0.0109, 0.0666, 0.6713],
        [0.3080, 0.1262, 0.7858],
        [0.5803, 0.4042, 0.9556],
        [0.3371, 0.9858, 0.8290]])

In [4]:
# 查看x的形状
print(x.size())

torch.Size([5, 3])


In [7]:
y = t.rand(5, 3)
print(y)
# 3种加法
print(x + y)
print(t.add(x, y))
result = t.Tensor(5, 3)
t.add(x, y, out=result)
print(result)

tensor([[0.1461, 0.3779, 0.1834],
        [0.9683, 0.7272, 0.6269],
        [0.8087, 0.9414, 0.8622],
        [0.6123, 0.4662, 0.2814],
        [0.4456, 0.5415, 0.8260]])
tensor([[0.3619, 1.2338, 0.1933],
        [0.9792, 0.7938, 1.2983],
        [1.1167, 1.0676, 1.6480],
        [1.1926, 0.8704, 1.2370],
        [0.7827, 1.5273, 1.6550]])
tensor([[0.3619, 1.2338, 0.1933],
        [0.9792, 0.7938, 1.2983],
        [1.1167, 1.0676, 1.6480],
        [1.1926, 0.8704, 1.2370],
        [0.7827, 1.5273, 1.6550]])
tensor([[0.3619, 1.2338, 0.1933],
        [0.9792, 0.7938, 1.2983],
        [1.1167, 1.0676, 1.6480],
        [1.1926, 0.8704, 1.2370],
        [0.7827, 1.5273, 1.6550]])


In [8]:
# 函数名后带下划线的函数会修改Tensor本身
print(x)
print(y)
y.add(x)
print(y)
y.add_(x)
print(y)

tensor([[0.2158, 0.8559, 0.0100],
        [0.0109, 0.0666, 0.6713],
        [0.3080, 0.1262, 0.7858],
        [0.5803, 0.4042, 0.9556],
        [0.3371, 0.9858, 0.8290]])
tensor([[0.1461, 0.3779, 0.1834],
        [0.9683, 0.7272, 0.6269],
        [0.8087, 0.9414, 0.8622],
        [0.6123, 0.4662, 0.2814],
        [0.4456, 0.5415, 0.8260]])
tensor([[0.1461, 0.3779, 0.1834],
        [0.9683, 0.7272, 0.6269],
        [0.8087, 0.9414, 0.8622],
        [0.6123, 0.4662, 0.2814],
        [0.4456, 0.5415, 0.8260]])
tensor([[0.3619, 1.2338, 0.1933],
        [0.9792, 0.7938, 1.2983],
        [1.1167, 1.0676, 1.6480],
        [1.1926, 0.8704, 1.2370],
        [0.7827, 1.5273, 1.6550]])


In [9]:
# Tensor不支持的操作，可以先转为numpy处理，之后 再转回Tensor。
# Tensor和numpy对象共享内存，所以转换非常快。
a = t.ones(5)
b = a.numpy()
c = t.from_numpy(b)
print(a)
print(b)
print(c)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.])


In [10]:
# Tensor可通过.cuda方法转为GPU的Tensor，从而 用GPU加速。 
# t.cuda.is_available()判断cuda是否可用。
if t.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

### 2.2.2 Autograd：自动微分
autograd.Variable是Autograd的核心类，它封装了Tensor，包括data/grad/grad_fn（指向一个function）。用.backware实现反向传播，自动计算梯度。

In [11]:
from torch.autograd import Variable
x = Variable(t.ones(2,2), requires_grad=True)

In [12]:
print(x)
y = x.sum()
print(y)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor(4., grad_fn=<SumBackward0>)


In [14]:
print(x.grad)
y.backward()
print(x.grad)

None
tensor([[1., 1.],
        [1., 1.]])
